/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/APDevTeam/Movecraft")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.citizensnpcs.co/")
    }

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations.java5)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.countercraft.movecraft)
    compileOnly(libs.net.citizensnpcs.citizensapi)
    compileOnly(libs.com.github.milkbowl.vaultapi)
    system(libs.com.degitise.minevid.dtltraders)
}

group = "cccm5.github.io"
version = "2.0.0_beta-2"
description = "Cargo"
java.sourceCompatibility = JavaVersion.VERSION_13

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
